#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
xrdb ${HOME}/.Xresources
polybar example -r &
feh --bg-fill ~/Pictures/makiseback.jpg
picom --experimental-backends &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V


bspc config border_width         3
bspc config window_gap          15	

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#E6D4A3
bspc config normal_border_color \#222222
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a steam desktop='^3' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


